FROM node:lts-alpine

WORKDIR '/app'

COPY package*.json .
RUN npm install

# Intentionally skip copying src and public (rely on bind mounts to local source code)
# COPY . .

# EXPOSE 3000

CMD ["npm", "start"]
