services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hunlecb/frontend
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production # Set production environment
      - LOG_LEVEL=info # Set production log level
      - DATABASE_URL=postgres://prod_user:prod_password@prod_host:5432/proddb # Example: Production DB connection
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512MB
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
