FROM node:lts-alpine

WORKDIR '/app'

COPY package*.json .
RUN npm install

# Intentionally skip copying src and public (rely on bind mounts to local source code)
# COPY . .

# Use nodemon for development to auto-reload on changes
EXPOSE 3000

CMD ["npm", "start"]
